{{ if .Values.secrets.regCred.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.secrets.regCred.path }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.regCred.key }}
{{ end }}