apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titan-docs
spec:
  destination:
    name: ''
    namespace: titan-docs
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://gitlab.tinkarbuild.com/titan/swf-titan-docs.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-with-args
  project: default
  syncPolicy:
    automated: {}
